### ISSUE TITLE
 Configuring base URLs

### ISSUE THREAD

**Issue by Hanhsuki** [Hanhsuki/Web-automation-test#5]
- Môi trường dev, auto, stagging, production là gì? nó khác nhau như thế nào ạ?
- nó khác nhau như thế nào ạ? 
-  Khi test mình phải chạy trên tất cả môi trường này ạ?

**Comment by Jacobvu84** [comment]
- Môi trường dev, auto, stagging, production là gì? nó khác nhau như thế nào ạ?
- nó khác nhau như thế nào ạ?

Để tránh việc bị ảnh hưởng trong quá trình phát triển sản phẩm hoặc trong qúa trình test. Thường người ta sẽ deploy sản phẩm trên các môi trường khác nhau. 

Ví dụ trang web cần test là abc.com

Thì họ có thể tạo ra một database riêng, một. nhánh code riêng cho mỗi mục đích. 

Để dev tập trung phát triển họ sẽ tạo ra dev.abc.com. Domain này sẽ trở tới một server khác.

Để tester tập trung kiểm tra sản phẩm Trong khi dev đang làm tính nămg mới khác thì họ tạo ra môi trường dành riêng cho test ví dụ. manual.abc.com

Để chạy kịch bản auto họ sẽ tạo ra một môi trường cho auto ví dụ auto.abc.com

Mục đích là ko để ảnh hưởng khi các đội làm việc chung

**Comment by Jacobvu84** [comment]
- Khi test mình phải chạy trên tất cả môi trường này ạ?

Tuỳ vào kế hoạch của người lập plan test. Họ muốn test môi trường nào thì chỉ cần thực hiện test trên môi trường đó.
