### ISSUE TITLE
Xây dựng phần Page (improve code)

### ISSUE THREAD

**Issue by Hanhsuki** [Hanhsuki/Web-automation-test#8]
1. public static final String TARGET = "//label[contains(text(), '%s')]/following-sibling::input"; 
%s là để làm gì ạ.

**Comment by Jacobvu84** [comment]
@Hanhsuki 
Để hiểu rõ hơn về điều này em học thêm về format String. 

Trong một String nếu chỗ nào có %s thì nó sẽ được thay thế bởi giá trị em muốn đưa vào.

Ví dụ

String myText = "Tôi tên là: Hanhsuki";

Nhưng nếu em muốn giữ cái định dạng "Tôi tên là: " sau đó có thể truyền tên bất kỳ. em có thể viết như sau

String myName = "Hanhsuki";

String myText = String.format("Tôi tên là: %s", myName);

Nó cũng sẽ trả lại giá trị myText = "Tôi tên là: Hanhsuki"

E học đọc thêm về 

- https://viblo.asia/p/java-string-format-6J3ZgkXgZmB ( Tiếng Việt)
- https://dzone.com/articles/java-string-format-examples ( English)

Khuyến khích đọc tài liệu và học thêm từ vững chuyên ngành IT bằng English.
