### ISSUE TITLE
[Serenity #15] Kiểm tra test với junit

### ISSUE THREAD

**Issue by Hanhsuki** [Hanhsuki/Web-automation-test#9]

**Comment by Hanhsuki** [comment]
The problem ( Vấn đề mắc phải)
Trong bài này khi em chạy test với câu lệnh: mvn clean verify -D.ittest=WhenRegisterNewAccount để chạy mình class "WhenRegisterNewAccount". Nhưng khi chạy test thì lại chạy cả class "WhenOpeningTheWeb" sau đó mới chạy class "mvn clean verify -D.ittest=WhenRegisterNewAccount"

Thực hành theo video:
[Serenity #15] Kiểm tra kết quả test với Junit
https://www.youtube.com/watch?v=6lhi_mwPswU&list=PLpTCO0Fa9GR38qJ-AtT0EWJf5mDP7CXwJ&index=16

Commit code mới nhất:
https://github.com/Hanhsuki/Web-automation-test/commit/b945bef24e9da40cd598966f898c3574f67f6ba2

**Comment by teachingwebdrivervideo** [comment]
-D.ittest=WhenRegisterNewAccount bị sai.

nó là `-Dit.test=WhenRegisterNewAccount`
